In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_json('../data/candidates.jsonl', lines=True)

In [5]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [9]:
flat_df = pd.json_normalize(df.to_dict(orient="records"), sep="_")
flat_df.head()

,candidate_id,career_history,education,skills,certifications,languages,profile_anonymized_name,profile_headline,profile_summary,profile_location,...,redrob_signals_skill_assessment_scores_Python,redrob_signals_skill_assessment_scores_OpenSearch,redrob_signals_skill_assessment_scores_BM25,redrob_signals_skill_assessment_scores_scikit-learn,redrob_signals_skill_assessment_scores_pgvector,redrob_signals_skill_assessment_scores_Embeddings,redrob_signals_skill_assessment_scores_LlamaIndex,redrob_signals_skill_assessment_scores_PyTorch,redrob_signals_skill_assessment_scores_Deep Learning,redrob_signals_skill_assessment_scores_QLoRA
0,CAND_0000001,"[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...",Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAND_0000002,"[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'Local Engineering College', ...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...",Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAND_0000003,"[{'company': 'TCS', 'title': 'Customer Support...","[{'institution': 'Local Engineering College', ...","[{'name': 'Angular', 'proficiency': 'intermedi...",[],"[{'language': 'English', 'proficiency': 'profe...",Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAND_0000004,"[{'company': 'Dunder Mifflin', 'title': 'Marke...","[{'institution': 'Local Engineering College', ...","[{'name': 'Node.js', 'proficiency': 'intermedi...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...",Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAND_0000005,"[{'company': 'Stark Industries', 'title': 'Acc...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'SQL', 'proficiency': 'beginner', 'e...",[],"[{'language': 'English', 'proficiency': 'profe...",Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
flat_df.columns

Index(['candidate_id', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'profile_anonymized_name',
       'profile_headline', 'profile_summary', 'profile_location',
       'profile_country', 'profile_years_of_experience',
       'profile_current_title', 'profile_current_company',
       'profile_current_company_size', 'profile_current_industry',
       'redrob_signals_profile_completeness_score',
       'redrob_signals_signup_date', 'redrob_signals_last_active_date',
       'redrob_signals_open_to_work_flag',
       'redrob_signals_profile_views_received_30d',
       'redrob_signals_applications_submitted_30d',
       'redrob_signals_recruiter_response_rate',
       'redrob_signals_avg_response_time_hours',
       'redrob_signals_skill_assessment_scores_NLP',
       'redrob_signals_skill_assessment_scores_Image Classification',
       'redrob_signals_skill_assessment_scores_Fine-tuning LLMs',
       'redrob_signals_skill_assessment_scores_Speech Recognition',
       'redrob_signals_connection_count',
       'redrob_signals_endorsements_received',
       'redrob_signals_notice_period_days',
       'redrob_signals_expected_salary_range_inr_lpa_min',
       'redrob_signals_expected_salary_range_inr_lpa_max',
       'redrob_signals_preferred_work_mode',
       'redrob_signals_willing_to_relocate',
       'redrob_signals_github_activity_score',
       'redrob_signals_search_appearance_30d',
       'redrob_signals_saved_by_recruiters_30d',
       'redrob_signals_interview_completion_rate',
       'redrob_signals_offer_acceptance_rate', 'redrob_signals_verified_email',
       'redrob_signals_verified_phone', 'redrob_signals_linkedin_connected',
       'redrob_signals_skill_assessment_scores_GANs',
       'redrob_signals_skill_assessment_scores_OpenCV',
       'redrob_signals_skill_assessment_scores_Prompt Engineering',
       'redrob_signals_skill_assessment_scores_Object Detection',
       'redrob_signals_skill_assessment_scores_Recommendation Systems',
       'redrob_signals_skill_assessment_scores_FAISS',
       'redrob_signals_skill_assessment_scores_Weights & Biases',
       'redrob_signals_skill_assessment_scores_Forecasting',
       'redrob_signals_skill_assessment_scores_LangChain',
       'redrob_signals_skill_assessment_scores_YOLO',
       'redrob_signals_skill_assessment_scores_PEFT',
       'redrob_signals_skill_assessment_scores_Data Science',
       'redrob_signals_skill_assessment_scores_MLflow',
       'redrob_signals_skill_assessment_scores_Pinecone',
       'redrob_signals_skill_assessment_scores_Feature Engineering',
       'redrob_signals_skill_assessment_scores_BentoML',
       'redrob_signals_skill_assessment_scores_MLOps',
       'redrob_signals_skill_assessment_scores_Qdrant',
       'redrob_signals_skill_assessment_scores_CNN',
       'redrob_signals_skill_assessment_scores_Kubeflow',
       'redrob_signals_skill_assessment_scores_Machine Learning',
       'redrob_signals_skill_assessment_scores_Reinforcement Learning',
       'redrob_signals_skill_assessment_scores_Sentence Transformers',
       'redrob_signals_skill_assessment_scores_Haystack',
       'redrob_signals_skill_assessment_scores_Hugging Face Transformers',
       'redrob_signals_skill_assessment_scores_Semantic Search',
       'redrob_signals_skill_assessment_scores_LoRA',
       'redrob_signals_skill_assessment_scores_Diffusion Models',
       'redrob_signals_skill_assessment_scores_Milvus',
       'redrob_signals_skill_assessment_scores_Time Series',
       'redrob_signals_skill_assessment_scores_Statistical Modeling',
       'redrob_signals_skill_assessment_scores_Elasticsearch',
       'redrob_signals_skill_assessment_scores_Information Retrieval',
       'redrob_signals_skill_assessment_scores_Vector Search',
       'redrob_signals_skill_assessment_scores_Learning to Rank',
       'redrob_signals_skill_assessment_scores_ASR',
       'redrob_signals_skill_assessment_scores_TensorFlow',
       'redrob_signals_skill_assessment_scores_LLMs',
       'redrob_signals_skill_assessment_scores_Computer Vision',
       'redrob_signals_skill_assessment_scores_TTS',
       'redrob_signals_skill_assessment_scores_Weaviate',
       'redrob_signals_skill_assessment_scores_RAG',
       'redrob_signals_skill_assessment_scores_Python',
       'redrob_signals_skill_assessment_scores_OpenSearch',
       'redrob_signals_skill_assessment_scores_BM25',
       'redrob_signals_skill_assessment_scores_scikit-learn',
       'redrob_signals_skill_assessment_scores_pgvector',
       'redrob_signals_skill_assessment_scores_Embeddings',
       'redrob_signals_skill_assessment_scores_LlamaIndex',
       'redrob_signals_skill_assessment_scores_PyTorch',
       'redrob_signals_skill_assessment_scores_Deep Learning',
       'redrob_signals_skill_assessment_scores_QLoRA'],
      dtype='str')

In [11]:
sample_df = df.sample(n=120, random_state=42)
sample_df.to_json('../data/candidates_sample_120.jsonl', orient='records', lines=True)
sample_df.head()

,candidate_id,profile,career_history,education,skills,certifications,languages,redrob_signals
75721,CAND_0075722,"{'anonymized_name': 'Aisha Goyal', 'headline':...","[{'company': 'Acme Corp', 'title': 'Cloud Engi...","[{'institution': 'IISc Bangalore', 'degree': '...","[{'name': 'MLflow', 'proficiency': 'advanced',...","[{'name': 'Scrum Master Certified', 'issuer': ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 55.1, 'signup_d..."
80184,CAND_0080185,"{'anonymized_name': 'Riya Shetty', 'headline':...","[{'company': 'Wayne Enterprises', 'title': 'Ac...","[{'institution': 'Amity University', 'degree':...","[{'name': 'Redis', 'proficiency': 'beginner', ...","[{'name': 'Scrum Master Certified', 'issuer': ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 42.2, 'signup_d..."
19864,CAND_0019865,"{'anonymized_name': 'Saanvi Singh', 'headline'...","[{'company': 'Stark Industries', 'title': 'Pro...","[{'institution': 'VJTI Mumbai', 'degree': 'B.S...","[{'name': 'Angular', 'proficiency': 'beginner'...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 74.5, 'signup_d..."
76699,CAND_0076700,"{'anonymized_name': 'Saanvi Arora', 'headline'...","[{'company': 'Stark Industries', 'title': 'Bus...","[{'institution': 'Bharati Vidyapeeth', 'degree...","[{'name': 'Go', 'proficiency': 'intermediate',...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 50.9, 'signup_d..."
92991,CAND_0092992,"{'anonymized_name': 'Neha Saxena', 'headline':...","[{'company': 'Acme Corp', 'title': '.NET Devel...","[{'institution': 'Amity University', 'degree':...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 85.8, 'signup_d..."

In [12]:
# Create a dataset excluding the sample data
exclude_ids = set(sample_df['candidate_id'])
filtered_df = df[~df['candidate_id'].isin(exclude_ids)].reset_index(drop=True)

# Save the filtered dataset
filtered_df.to_json('../data/candidates_excluding_sample.jsonl', orient='records', lines=True)

print(f"Original dataset size: {len(df)}")
print(f"Sample dataset size: {len(sample_df)}")
print(f"Filtered dataset size: {len(filtered_df)}")
print(f"Filtered dataset saved to '../data/candidates_excluding_sample.jsonl'")

Original dataset size: 100000
Sample dataset size: 120
Filtered dataset size: 99880
Filtered dataset saved to '../data/candidates_excluding_sample.jsonl'

In [13]:
filtered_df.head()

,candidate_id,profile,career_history,education,skills,certifications,languages,redrob_signals
0,CAND_0000001,"{'anonymized_name': 'Ira Vora', 'headline': 'B...","[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 86.9, 'signup_d..."
1,CAND_0000002,"{'anonymized_name': 'Saanvi Sethi', 'headline'...","[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'Local Engineering College', ...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 78.7, 'signup_d..."
2,CAND_0000003,"{'anonymized_name': 'Yash Agarwal', 'headline'...","[{'company': 'TCS', 'title': 'Customer Support...","[{'institution': 'Local Engineering College', ...","[{'name': 'Angular', 'proficiency': 'intermedi...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 31.9, 'signup_d..."
3,CAND_0000004,"{'anonymized_name': 'Anil Bose', 'headline': '...","[{'company': 'Dunder Mifflin', 'title': 'Marke...","[{'institution': 'Local Engineering College', ...","[{'name': 'Node.js', 'proficiency': 'intermedi...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 28.5, 'signup_d..."
4,CAND_0000005,"{'anonymized_name': 'Aisha Sethi', 'headline':...","[{'company': 'Stark Industries', 'title': 'Acc...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'SQL', 'proficiency': 'beginner', 'e...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 84.6, 'signup_d..."

In [23]:
import json
from collections import Counter

jsonl_path = '../data/candidates_excluding_sample.jsonl'

# ── Domain exclusion config ──────────────────────────────────────────────────

WRONG_TITLE_KEYWORDS = [
    "marketing", "sales", "hr ", "human resource", "recruiter", "talent acquisition",
    "finance", "accountant", "accounting", "business development", "bd manager",
    "supply chain", "logistics", "operations manager", "project manager",
    "product manager",
    "graphic design", "ux designer", "ui designer", "visual design",
    "content writer", "copywriter", "seo", "social media",
    "civil engineer", "mechanical engineer", "electrical engineer",
    "hardware engineer", "embedded", "firmware",
    "computer vision", "cv engineer",
    "speech", "audio", "robotics", "autonomous",
    "teacher", "professor", "lecturer", "faculty",
    "doctor", "physician", "nurse", "pharmacist",
    "lawyer", "legal", "compliance",
    "customer success", "customer support", "support engineer",
]

# ── Helpers ──────────────────────────────────────────────────────────────────

def matches_any(text, keywords):
    t = text.lower()
    return any(kw in t for kw in keywords)

# ── Main pass ────────────────────────────────────────────────────────────────

country_counter = Counter()
title_counter   = Counter()

non_india_ids   = []
wrong_title_ids = []

INDIA_VARIANTS = {"india", "in", "ind"}

total = 0
with open(jsonl_path) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        c = json.loads(line)
        total += 1
        p = c["profile"]
        cid = c["candidate_id"]

        country = p.get("country", "").strip()
        title   = p.get("current_title", "").strip()

        # ── Country ──────────────────────────────────────────────────────────
        country_counter[country] += 1
        if country.lower() not in INDIA_VARIANTS:
            willing = c.get("redrob_signals", {}).get("willing_to_relocate", False)
            if not willing:
                non_india_ids.append((cid, country, willing))

        # ── Wrong title ──────────────────────────────────────────────────────
        title_counter[title] += 1
        if matches_any(title, WRONG_TITLE_KEYWORDS):
            wrong_title_ids.append((cid, title))

# ── Results ──────────────────────────────────────────────────────────────────

print("=" * 60)
print(f"TOTAL CANDIDATES PROCESSED: {total:,}")
print("=" * 60)

# 1. Country distribution
print("\n── TOP 30 COUNTRIES ──")
for country, cnt in country_counter.most_common(30):
    pct = cnt / total * 100
    flag = " ← INDIA" if country.lower() in INDIA_VARIANTS else ""
    print(f"  {country:<30} {cnt:>6,}  ({pct:.1f}%){flag}")

print(f"\n  Total unique countries: {len(country_counter)}")
print(f"\n  Non-India AND not willing to relocate: {len(non_india_ids):,}")
non_india_country_counter = Counter(c for _, c, _ in non_india_ids)
print("  Top non-India (not relocating) countries:")
for country, cnt in non_india_country_counter.most_common(15):
    print(f"    {country:<30} {cnt:>5,}")

# 2. Wrong title
print(f"\n── WRONG TITLE (clearly off-domain) ──")
print(f"  Candidates with wrong-domain title: {len(wrong_title_ids):,}")
print("  Top offending titles:")
wrong_title_top = Counter(t for _, t in wrong_title_ids)
for title, cnt in wrong_title_top.most_common(20):
    print(f"    {title:<45} {cnt:>5,}")

# 3. Combined exclusion
excluded_ids = set(cid for cid, _, _ in non_india_ids) \
             | set(cid for cid, _ in wrong_title_ids)

print(f"\n── COMBINED EXCLUSION ESTIMATE ──")
print(f"  Non-India (no relocation):  {len(non_india_ids):>6,}")
print(f"  Wrong title:                {len(wrong_title_ids):>6,}")
print(f"  Union (unique excluded):    {len(excluded_ids):>6,}  ({len(excluded_ids)/total*100:.1f}%)")
print(f"  Remaining after exclusion:  {total - len(excluded_ids):>6,}")

============================================================
TOTAL CANDIDATES PROCESSED: 99,880
============================================================

── TOP 30 COUNTRIES ──
  India                          75,017  (75.1%) ← INDIA
  USA                             9,963  (10.0%)
  Australia                       2,577  (2.6%)
  Canada                          2,504  (2.5%)
  UK                              2,471  (2.5%)
  Germany                         2,467  (2.5%)
  Singapore                       2,453  (2.5%)
  UAE                             2,428  (2.4%)

  Total unique countries: 8

  Non-India AND not willing to relocate: 17,735
  Top non-India (not relocating) countries:
    USA                            7,074
    Australia                      1,842
    Canada                         1,804
    Germany                        1,771
    Singapore                      1,763
    UK                             1,757
    UAE                            1,724

── WRONG TITLE (clearly off-domain) ──
  Candidates with wrong-domain title: 63,049
  Top offending titles:
    HR Manager                                    5,819
    Mechanical Engineer                           5,784
    Accountant                                    5,757
    Project Manager                               5,748
    Customer Support                              5,744
    Operations Manager                            5,740
    Content Writer                                5,719
    Sales Executive                               5,707
    Civil Engineer                                5,697
    Graphic Designer                              5,682
    Marketing Manager                             5,521
    Computer Vision Engineer                        131

── COMBINED EXCLUSION ESTIMATE ──
  Non-India (no relocation):  17,735
  Wrong title:                63,049
  Union (unique excluded):    69,418  (69.5%)
  Remaining after exclusion:  30,462

In [19]:
industry_counter

Counter({'IT Services': 29842,
         'Software': 22394,
         'Manufacturing': 22272,
         'Conglomerate': 7561,
         'Paper Products': 7458,
         'Fintech': 2808,
         'Food Delivery': 2513,
         'E-commerce': 1528,
         'Consulting': 1273,
         'EdTech': 609,
         'SaaS': 328,
         'AI/ML': 277,
         'AdTech': 172,
         'Transportation': 162,
         'Insurance Tech': 155,
         'Gaming': 149,
         'HealthTech': 147,
         'HealthTech AI': 68,
         'Conversational AI': 61,
         'AI Services': 42,
         'Voice AI': 31,
         'Internet': 22,
         'Media': 6,
         'Consumer Electronics': 2})

In [20]:
title_counter

Counter({'Business Analyst': 5824,
         'HR Manager': 5819,
         'Mechanical Engineer': 5784,
         'Accountant': 5757,
         'Project Manager': 5748,
         'Customer Support': 5744,
         'Operations Manager': 5740,
         'Content Writer': 5719,
         'Sales Executive': 5707,
         'Civil Engineer': 5697,
         'Graphic Designer': 5682,
         'Marketing Manager': 5521,
         'Software Engineer': 3447,
         'Full Stack Developer': 2869,
         'Cloud Engineer': 2834,
         'Java Developer': 2806,
         '.NET Developer': 2785,
         'DevOps Engineer': 2782,
         'Mobile Developer': 2753,
         'Frontend Engineer': 2730,
         'QA Engineer': 2678,
         'Analytics Engineer': 764,
         'Data Engineer': 744,
         'Data Analyst': 728,
         'Backend Engineer': 703,
         'Senior Data Engineer': 686,
         'Senior Software Engineer': 652,
         'ML Engineer': 167,
         'AI Research Engineer': 152,
         'Data Scientist': 145,
         'Senior Software Engineer (ML)': 142,
         'Computer Vision Engineer': 131,
         'Junior ML Engineer': 131,
         'AI Specialist': 130,
         'Recommendation Systems Engineer': 26,
         'Machine Learning Engineer': 24,
         'Applied ML Engineer': 23,
         'Search Engineer': 23,
         'AI Engineer': 21,
         'Senior Data Scientist': 19,
         'NLP Engineer': 14,
         'Senior NLP Engineer': 6,
         'Senior Machine Learning Engineer': 6,
         'Staff Machine Learning Engineer': 6,
         'Senior AI Engineer': 4,
         'Senior Applied Scientist': 4,
         'Lead AI Engineer': 3})

In [22]:
import json
from collections import Counter

jsonl_path = '../data/candidates_excluding_sample.jsonl'

# ── Domain exclusion config ──────────────────────────────────────────────────

WRONG_TITLE_KEYWORDS = [
    "marketing", "sales", "hr ", "human resource", "recruiter", "talent acquisition",
    "finance", "accountant", "accounting", "business development", "bd manager",
    "supply chain", "logistics", "operations manager", "project manager",
    "product manager",
    "graphic design", "ux designer", "ui designer", "visual design",
    "content writer", "copywriter", "seo", "social media",
    "civil engineer", "mechanical engineer", "electrical engineer",
    "hardware engineer", "embedded", "firmware",
    "computer vision", "cv engineer",
    "speech", "audio", "robotics", "autonomous",
    "teacher", "professor", "lecturer", "faculty",
    "doctor", "physician", "nurse", "pharmacist",
    "lawyer", "legal", "compliance",
    "customer success", "customer support", "support engineer",
]

# ── Helpers ──────────────────────────────────────────────────────────────────

def matches_any(text, keywords):
    t = text.lower()
    return any(kw in t for kw in keywords)

# ── Main pass ────────────────────────────────────────────────────────────────

country_counter = Counter()
title_counter   = Counter()

non_india_ids   = []
wrong_title_ids = []

INDIA_VARIANTS = {"india", "in", "ind"}

total = 0
with open(jsonl_path) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        c = json.loads(line)
        total += 1
        p = c["profile"]
        cid = c["candidate_id"]

        country = p.get("country", "").strip()
        title   = p.get("current_title", "").strip()

        # ── Country ──────────────────────────────────────────────────────────
        country_counter[country] += 1
        if country.lower() not in INDIA_VARIANTS:
            willing = c.get("redrob_signals", {}).get("willing_to_relocate", False)
            if not willing:
                non_india_ids.append((cid, country, willing))

        # ── Wrong title ──────────────────────────────────────────────────────
        title_counter[title] += 1
        if matches_any(title, WRONG_TITLE_KEYWORDS):
            wrong_title_ids.append((cid, title))

# ── Results ──────────────────────────────────────────────────────────────────

print("=" * 60)
print(f"TOTAL CANDIDATES PROCESSED: {total:,}")
print("=" * 60)

# 1. Country distribution
print("\n── TOP 30 COUNTRIES ──")
for country, cnt in country_counter.most_common(30):
    pct = cnt / total * 100
    flag = " ← INDIA" if country.lower() in INDIA_VARIANTS else ""
    print(f"  {country:<30} {cnt:>6,}  ({pct:.1f}%){flag}")

print(f"\n  Total unique countries: {len(country_counter)}")
print(f"\n  Non-India AND not willing to relocate: {len(non_india_ids):,}")
non_india_country_counter = Counter(c for _, c, _ in non_india_ids)
print("  Top non-India (not relocating) countries:")
for country, cnt in non_india_country_counter.most_common(15):
    print(f"    {country:<30} {cnt:>5,}")

# 2. Wrong title
print(f"\n── WRONG TITLE (clearly off-domain) ──")
print(f"  Candidates with wrong-domain title: {len(wrong_title_ids):,}")
print("  Top offending titles:")
wrong_title_top = Counter(t for _, t in wrong_title_ids)
for title, cnt in wrong_title_top.most_common(20):
    print(f"    {title:<45} {cnt:>5,}")

# 3. Combined exclusion
excluded_ids = set(cid for cid, _, _ in non_india_ids) \
             | set(cid for cid, _ in wrong_title_ids)

print(f"\n── COMBINED EXCLUSION ESTIMATE ──")
print(f"  Non-India (no relocation):  {len(non_india_ids):>6,}")
print(f"  Wrong title:                {len(wrong_title_ids):>6,}")
print(f"  Union (unique excluded):    {len(excluded_ids):>6,}  ({len(excluded_ids)/total*100:.1f}%)")
print(f"  Remaining after exclusion:  {total - len(excluded_ids):>6,}")

============================================================
TOTAL CANDIDATES PROCESSED: 99,880
============================================================

── TOP 30 COUNTRIES ──
  India                          75,017  (75.1%) ← INDIA
  USA                             9,963  (10.0%)
  Australia                       2,577  (2.6%)
  Canada                          2,504  (2.5%)
  UK                              2,471  (2.5%)
  Germany                         2,467  (2.5%)
  Singapore                       2,453  (2.5%)
  UAE                             2,428  (2.4%)

  Total unique countries: 8

  Non-India AND not willing to relocate: 17,735
  Top non-India (not relocating) countries:
    USA                            7,074
    Australia                      1,842
    Canada                         1,804
    Germany                        1,771
    Singapore                      1,763
    UK                             1,757
    UAE                            1,724

── WRONG TITLE (clearly off-domain) ──
  Candidates with wrong-domain title: 63,049
  Top offending titles:
    HR Manager                                    5,819
    Mechanical Engineer                           5,784
    Accountant                                    5,757
    Project Manager                               5,748
    Customer Support                              5,744
    Operations Manager                            5,740
    Content Writer                                5,719
    Sales Executive                               5,707
    Civil Engineer                                5,697
    Graphic Designer                              5,682
    Marketing Manager                             5,521
    Computer Vision Engineer                        131

── COMBINED EXCLUSION ESTIMATE ──
  Non-India (no relocation):  17,735
  Wrong title:                63,049
  Union (unique excluded):    69,418  (69.5%)
  Remaining after exclusion:  30,462

In [ ]:
import json
from collections import Counter

jsonl_path = '../data/candidates_excluding_sample.jsonl'

# ── Previously excluded IDs (pass these in from your earlier filter step) ────
# excluded_ids = set(...)  # from your country + title filter

WRONG_TITLE_KEYWORDS = [
    "marketing", "sales", "hr ", "human resource", "recruiter", "talent acquisition",
    "finance", "accountant", "accounting", "business development", "bd manager",
    "supply chain", "logistics", "operations manager", "project manager",
    "product manager",
    "graphic design", "ux designer", "ui designer", "visual design",
    "content writer", "copywriter", "seo", "social media",
    "civil engineer", "mechanical engineer", "electrical engineer",
    "hardware engineer", "embedded", "firmware",
    "computer vision", "cv engineer",
    "speech", "audio", "robotics", "autonomous",
    "teacher", "professor", "lecturer", "faculty",
    "doctor", "physician", "nurse", "pharmacist",
    "lawyer", "legal", "compliance",
    "customer success", "customer support", "support engineer",
]

INDIA_VARIANTS = {"india", "in", "ind"}

def matches_any(text, keywords):
    return any(kw in text.lower() for kw in keywords)

# ── Thresholds ────────────────────────────────────────────────────────────────
MIN_YOE = 3      # less than this → too junior
MAX_YOE = 20     # more than this → likely data error / irrelevant

# ── Counters & buckets ────────────────────────────────────────────────────────
country_counter = Counter()
title_counter   = Counter()
yoe_distribution = Counter()  # bucketed

non_india_ids        = []
wrong_title_ids      = []
too_junior_ids       = []
too_senior_ids       = []
honeypot_skill_ids   = []
null_skills_ids      = []

total = 0
passed = []  # candidates surviving ALL filters

with open(jsonl_path) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        c = json.loads(line)
        total += 1
        p   = c["profile"]
        cid = c["candidate_id"]

        country = p.get("country", "").strip()
        title   = p.get("current_title", "").strip()
        yoe     = p.get("years_of_experience", 0) or 0
        skills  = c.get("skills") or []  # handles both null and []

        # ── bucket yoe for distribution printout ─────────────────────────────
        bucket = (int(yoe) // 2) * 2          # 0-1, 2-3, 4-5 ...
        yoe_distribution[bucket] += 1

        exclude_reasons = []

        # ── Filter 1: country ─────────────────────────────────────────────────
        country_counter[country] += 1
        if country.lower() not in INDIA_VARIANTS:
            willing = c.get("redrob_signals", {}).get("willing_to_relocate", False)
            if not willing:
                non_india_ids.append((cid, country))
                exclude_reasons.append("non_india")

        # ── Filter 2: wrong title ─────────────────────────────────────────────
        title_counter[title] += 1
        if matches_any(title, WRONG_TITLE_KEYWORDS):
            wrong_title_ids.append((cid, title))
            exclude_reasons.append("wrong_title")

        # ── Filter 3: years of experience extremes ────────────────────────────
        if yoe < MIN_YOE:
            too_junior_ids.append((cid, yoe))
            exclude_reasons.append("too_junior")
        elif yoe > MAX_YOE:
            too_senior_ids.append((cid, yoe))
            exclude_reasons.append("too_senior")

        # ── Filter 4: null / empty skills ────────────────────────────────────
        if not skills:
            null_skills_ids.append(cid)
            exclude_reasons.append("null_skills")

        # ── Filter 5: honeypot — expert skill with duration_months = 0 ───────
        # flag only if ALL expert skills have duration_months = 0
        # (one bad entry could be a data glitch; all bad = honeypot)
        if skills:
            expert_skills = [s for s in skills if s.get("proficiency") == "expert"]
            if expert_skills and all(
                (s.get("duration_months") or 0) == 0 for s in expert_skills
            ):
                honeypot_skill_ids.append(
                    (cid, [(s["name"], s.get("duration_months")) for s in expert_skills])
                )
                exclude_reasons.append("honeypot_skill")

        if not exclude_reasons:
            passed.append(cid)

# ── Results ───────────────────────────────────────────────────────────────────

print("=" * 60)
print(f"TOTAL CANDIDATES: {total:,}")
print("=" * 60)

# YOE distribution
print("\n── YEARS OF EXPERIENCE DISTRIBUTION ──")
print(f"  {'YOE bucket':<15} {'count':>7}   bar")
for bucket in sorted(yoe_distribution):
    cnt = yoe_distribution[bucket]
    bar = "█" * (cnt // 200)
    label = f"{bucket}-{bucket+1}"
    marker = " ← MIN cutoff" if bucket == int(MIN_YOE // 2) * 2 else \
             " ← MAX cutoff" if bucket == int(MAX_YOE // 2) * 2 else ""
    print(f"  {label:<15} {cnt:>7,}   {bar}{marker}")
print(f"\n  Too junior (< {MIN_YOE} yoe):   {len(too_junior_ids):,}")
print(f"  Too senior (> {MAX_YOE} yoe):  {len(too_senior_ids):,}")

# Null skills
print(f"\n── NULL / EMPTY SKILLS ──")
print(f"  Candidates with no skills listed: {len(null_skills_ids):,}")

# Honeypot skills
print(f"\n── HONEYPOT SKILL SIGNAL ──")
print(f"  Candidates with ALL expert skills at duration_months=0: {len(honeypot_skill_ids):,}")
print("  Sample (first 10):")
for cid, skills_info in honeypot_skill_ids[:10]:
    print(f"    {cid}  →  {skills_info}")

# Combined
excluded_ids = (
    set(cid for cid, _ in non_india_ids)
    | set(cid for cid, _ in wrong_title_ids)
    | set(cid for cid, _ in too_junior_ids)
    | set(cid for cid, _ in too_senior_ids)
    | set(null_skills_ids)
    | set(cid for cid, _ in honeypot_skill_ids)
)

print(f"\n── COMBINED EXCLUSION SUMMARY ──")
print(f"  Non-India (no relocation):          {len(non_india_ids):>6,}")
print(f"  Wrong title:                        {len(wrong_title_ids):>6,}")
print(f"  Too junior (< {MIN_YOE} yoe):              {len(too_junior_ids):>6,}")
print(f"  Too senior (> {MAX_YOE} yoe):             {len(too_senior_ids):>6,}")
print(f"  Null/empty skills:                  {len(null_skills_ids):>6,}")
print(f"  Honeypot skill signal:              {len(honeypot_skill_ids):>6,}")
print(f"  ─────────────────────────────────────────")
print(f"  Union (unique excluded):            {len(excluded_ids):>6,}  ({len(excluded_ids)/total*100:.1f}%)")
print(f"  Remaining after ALL filters:        {len(passed):>6,}")

============================================================
TOTAL CANDIDATES: 99,880
============================================================

── YEARS OF EXPERIENCE DISTRIBUTION ──
  YOE bucket        count   bar
  0-1               7,465   █████████████████████████████████████
  2-3              17,557   ███████████████████████████████████████████████████████████████████████████████████████ ← MIN cutoff
  4-5              17,448   ███████████████████████████████████████████████████████████████████████████████████████
  6-7              17,227   ██████████████████████████████████████████████████████████████████████████████████████
  8-9              15,267   ████████████████████████████████████████████████████████████████████████████
  10-11            10,064   ██████████████████████████████████████████████████
  12-13             9,700   ████████████████████████████████████████████████
  14-15             5,147   █████████████████████████
  16-17                 5

  Too junior (< 3 yoe):   16,105
  Too senior (> 20 yoe):  0

── NULL / EMPTY SKILLS ──
  Candidates with no skills listed: 0

── HONEYPOT SKILL SIGNAL ──
  Candidates with ALL expert skills at duration_months=0: 21
  Sample (first 10):
    CAND_0003582  →  [('MLflow', 0), ('Photoshop', 0), ('Content Writing', 0)]
    CAND_0016000  →  [('TypeScript', 0), ('Go', 0), ('Docker', 0), ('Hadoop', 0), ('Photoshop', 0)]
    CAND_0033817  →  [('JavaScript', 0), ('BigQuery', 0), ('Six Sigma', 0), ('gRPC', 0)]
    CAND_0033972  →  [('Airflow', 0), ('OpenCV', 0), ('Figma', 0)]
    CAND_0036839  →  [('SAP', 0), ('GCP', 0), ('Rust', 0)]
    CAND_0042245  →  [('Databricks', 0), ('BentoML', 0), ('Vue.js', 0)]
    CAND_0046649  →  [('SAP', 0), ('Node.js', 0), ('gRPC', 0), ('Flask', 0), ('Hadoop', 0)]
    CAND_0046689  →  [('Node.js', 0), ('SQL', 0), ('gRPC', 0), ('Spark', 0)]
    CAND_0048740  →  [('gRPC', 0), ('Angular', 0), ('Content Writing', 0)]
    CAND_0055792  →  [('Scrum', 0), ('TTS', 0), ('LoRA', 0)]

── COMBINED EXCLUSION SUMMARY ──
  Non-India (no relocation):          17,735
  Wrong title:                        63,049
  Too junior (< 3 yoe):              16,105
  Too senior (> 20 yoe):                  0
  Null/empty skills:                       0
  Honeypot skill signal:                  21
  ─────────────────────────────────────────
  Union (unique excluded):            75,273  (75.4%)
  Remaining after ALL filters:        24,607

In [ ]:
import json
from collections import Counter

jsonl_path = '../data/candidates_excluding_sample.jsonl'

WRONG_TITLE_KEYWORDS = [
    "marketing", "sales", "hr ", "human resource", "recruiter", "talent acquisition",
    "finance", "accountant", "accounting", "business development", "bd manager",
    "supply chain", "logistics", "operations manager", "project manager",
    "product manager",
    "graphic design", "ux designer", "ui designer", "visual design",
    "content writer", "copywriter", "seo", "social media",
    "civil engineer", "mechanical engineer", "electrical engineer",
    "hardware engineer", "embedded", "firmware",
    "computer vision", "cv engineer",
    "speech", "audio", "robotics", "autonomous",
    "teacher", "professor", "lecturer", "faculty",
    "doctor", "physician", "nurse", "pharmacist",
    "lawyer", "legal", "compliance",
    "customer success", "customer support", "support engineer",
]

# ── Consulting firms from the JD's explicit disqualifier list ─────────────────
PURE_CONSULTING_FIRMS = {
    "tcs", "tata consultancy", "infosys", "wipro", "accenture",
    "cognizant", "capgemini", "hcl", "tech mahindra", "mphasis",
    "hexaware", "mindtree", "ltimindtree", "l&t infotech",
    "persistent systems", "niit technologies", "mastech",
    "kforce", "syntel", "unison",
}

INDIA_VARIANTS = {"india", "in", "ind"}

def matches_any(text, keywords):
    return any(kw in text.lower() for kw in keywords)

def is_consulting_firm(company_name):
    c = company_name.lower().strip()
    return any(firm in c for firm in PURE_CONSULTING_FIRMS)

def is_pure_consulting_career(career_history):
    """
    Returns True only if EVERY role in career history is at a consulting firm.
    If even one role is at a product company → keep the candidate (JD says that's fine).
    """
    if not career_history:
        return False
    return all(is_consulting_firm(role.get("company", "")) for role in career_history)

# ── Thresholds ────────────────────────────────────────────────────────────────
MIN_YOE = 3
MAX_YOE = 15

# ── Counters & buckets ────────────────────────────────────────────────────────
country_counter     = Counter()
title_counter       = Counter()
yoe_distribution    = Counter()
consulting_firm_counter = Counter()  # frequency of consulting firms seen

non_india_ids        = []
wrong_title_ids      = []
too_junior_ids       = []
too_senior_ids       = []
honeypot_skill_ids   = []
null_skills_ids      = []
pure_consulting_ids  = []

total = 0
passed = []

with open(jsonl_path) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        c = json.loads(line)
        total += 1
        p             = c["profile"]
        cid           = c["candidate_id"]
        career        = c.get("career_history") or []

        country = p.get("country", "").strip()
        title   = p.get("current_title", "").strip()
        yoe     = p.get("years_of_experience", 0) or 0
        skills  = c.get("skills") or []

        bucket = (int(yoe) // 2) * 2
        yoe_distribution[bucket] += 1

        exclude_reasons = []

        # ── Filter 1: country ─────────────────────────────────────────────────
        country_counter[country] += 1
        if country.lower() not in INDIA_VARIANTS:
            willing = c.get("redrob_signals", {}).get("willing_to_relocate", False)
            if not willing:
                non_india_ids.append((cid, country))
                exclude_reasons.append("non_india")

        # ── Filter 2: wrong title ─────────────────────────────────────────────
        title_counter[title] += 1
        if matches_any(title, WRONG_TITLE_KEYWORDS):
            wrong_title_ids.append((cid, title))
            exclude_reasons.append("wrong_title")

        # ── Filter 3: years of experience extremes ────────────────────────────
        if yoe < MIN_YOE:
            too_junior_ids.append((cid, yoe))
            exclude_reasons.append("too_junior")
        elif yoe > MAX_YOE:
            too_senior_ids.append((cid, yoe))
            exclude_reasons.append("too_senior")

        # ── Filter 4: null / empty skills ────────────────────────────────────
        if not skills:
            null_skills_ids.append(cid)
            exclude_reasons.append("null_skills")

        # ── Filter 5: honeypot skill signal ───────────────────────────────────
        if skills:
            expert_skills = [s for s in skills if s.get("proficiency") == "expert"]
            if expert_skills and all(
                (s.get("duration_months") or 0) == 0 for s in expert_skills
            ):
                honeypot_skill_ids.append(
                    (cid, [(s["name"], s.get("duration_months")) for s in expert_skills])
                )
                exclude_reasons.append("honeypot_skill")

        # ── Filter 6: pure consulting career ─────────────────────────────────
        # count firm appearances regardless (for the frequency report)
        for role in career:
            company = role.get("company", "")
            if is_consulting_firm(company):
                consulting_firm_counter[company] += 1

        if is_pure_consulting_career(career):
            companies = [r.get("company", "") for r in career]
            pure_consulting_ids.append((cid, companies))
            exclude_reasons.append("pure_consulting")

        if not exclude_reasons:
            passed.append(cid)

# ── Results ───────────────────────────────────────────────────────────────────

print("=" * 60)
print(f"TOTAL CANDIDATES: {total:,}")
print("=" * 60)

# YOE distribution
print("\n── YEARS OF EXPERIENCE DISTRIBUTION ──")
print(f"  {'YOE bucket':<15} {'count':>7}   bar")
for bucket in sorted(yoe_distribution):
    cnt = yoe_distribution[bucket]
    bar = "█" * (cnt // 200)
    label = f"{bucket}-{bucket+1}"
    marker = " ← MIN cutoff" if bucket == int(MIN_YOE // 2) * 2 else \
             " ← MAX cutoff" if bucket == int(MAX_YOE // 2) * 2 else ""
    print(f"  {label:<15} {cnt:>7,}   {bar}{marker}")
print(f"\n  Too junior (< {MIN_YOE} yoe):  {len(too_junior_ids):,}")
print(f"  Too senior (> {MAX_YOE} yoe): {len(too_senior_ids):,}")

# Null skills
print(f"\n── NULL / EMPTY SKILLS ──")
print(f"  Candidates with no skills listed: {len(null_skills_ids):,}")

# Honeypot skills
print(f"\n── HONEYPOT SKILL SIGNAL ──")
print(f"  Candidates with ALL expert skills at duration_months=0: {len(honeypot_skill_ids):,}")
print("  Sample (first 10):")
for cid, skills_info in honeypot_skill_ids[:10]:
    print(f"    {cid}  →  {skills_info}")

# Consulting firms
print(f"\n── CONSULTING FIRM FREQUENCY (all appearances in career history) ──")
for firm, cnt in consulting_firm_counter.most_common():
    print(f"  {firm:<40} {cnt:>6,}")
print(f"\n  Candidates with PURE consulting career: {len(pure_consulting_ids):,}")
print("  Sample (first 10):")
for cid, companies in pure_consulting_ids[:10]:
    print(f"    {cid}  →  {companies}")

# Combined
excluded_ids = (
    set(cid for cid, _ in non_india_ids)
    | set(cid for cid, _ in wrong_title_ids)
    | set(cid for cid, _ in too_junior_ids)
    | set(cid for cid, _ in too_senior_ids)
    | set(null_skills_ids)
    | set(cid for cid, _ in honeypot_skill_ids)
    | set(cid for cid, _ in pure_consulting_ids)
)

print(f"\n── COMBINED EXCLUSION SUMMARY ──")
print(f"  Non-India (no relocation):          {len(non_india_ids):>6,}")
print(f"  Wrong title:                        {len(wrong_title_ids):>6,}")
print(f"  Too junior (< {MIN_YOE} yoe):              {len(too_junior_ids):>6,}")
print(f"  Too senior (> {MAX_YOE} yoe):             {len(too_senior_ids):>6,}")
print(f"  Null/empty skills:                  {len(null_skills_ids):>6,}")
print(f"  Honeypot skill signal:              {len(honeypot_skill_ids):>6,}")
print(f"  Pure consulting career:             {len(pure_consulting_ids):>6,}")
print(f"  ─────────────────────────────────────────")
print(f"  Union (unique excluded):            {len(excluded_ids):>6,}  ({len(excluded_ids)/total*100:.1f}%)")
print(f"  Remaining after ALL filters:        {len(passed):>6,}")

============================================================
TOTAL CANDIDATES: 99,880
============================================================

── YEARS OF EXPERIENCE DISTRIBUTION ──
  YOE bucket        count   bar
  0-1               7,465   █████████████████████████████████████
  2-3              17,557   ███████████████████████████████████████████████████████████████████████████████████████ ← MIN cutoff
  4-5              17,448   ███████████████████████████████████████████████████████████████████████████████████████
  6-7              17,227   ██████████████████████████████████████████████████████████████████████████████████████
  8-9              15,267   ████████████████████████████████████████████████████████████████████████████
  10-11            10,064   ██████████████████████████████████████████████████
  12-13             9,700   ████████████████████████████████████████████████
  14-15             5,147   █████████████████████████ ← MAX cutoff
  16-17                 5

  Too junior (< 3 yoe):  16,105
  Too senior (> 15 yoe): 7

── NULL / EMPTY SKILLS ──
  Candidates with no skills listed: 0

── HONEYPOT SKILL SIGNAL ──
  Candidates with ALL expert skills at duration_months=0: 21
  Sample (first 10):
    CAND_0003582  →  [('MLflow', 0), ('Photoshop', 0), ('Content Writing', 0)]
    CAND_0016000  →  [('TypeScript', 0), ('Go', 0), ('Docker', 0), ('Hadoop', 0), ('Photoshop', 0)]
    CAND_0033817  →  [('JavaScript', 0), ('BigQuery', 0), ('Six Sigma', 0), ('gRPC', 0)]
    CAND_0033972  →  [('Airflow', 0), ('OpenCV', 0), ('Figma', 0)]
    CAND_0036839  →  [('SAP', 0), ('GCP', 0), ('Rust', 0)]
    CAND_0042245  →  [('Databricks', 0), ('BentoML', 0), ('Vue.js', 0)]
    CAND_0046649  →  [('SAP', 0), ('Node.js', 0), ('gRPC', 0), ('Flask', 0), ('Hadoop', 0)]
    CAND_0046689  →  [('Node.js', 0), ('SQL', 0), ('gRPC', 0), ('Spark', 0)]
    CAND_0048740  →  [('gRPC', 0), ('Angular', 0), ('Content Writing', 0)]
    CAND_0055792  →  [('Scrum', 0), ('TTS', 0), ('LoRA', 0)]

── CONSULTING FIRM FREQUENCY (all appearances in career history) ──
  Infosys                                  23,693
  Wipro                                    23,645
  TCS                                      23,459
  HCL                                       2,892
  Capgemini                                 2,884
  Mindtree                                  2,876
  Accenture                                 2,868
  Cognizant                                 2,858
  Tech Mahindra                             2,834
  Mphasis                                   2,820

  Candidates with PURE consulting career: 9,737
  Sample (first 10):
    CAND_0000003  →  ['TCS']
    CAND_0000008  →  ['Wipro']
    CAND_0000024  →  ['TCS', 'Infosys']
    CAND_0000027  →  ['Infosys', 'Wipro']
    CAND_0000028  →  ['Wipro']
    CAND_0000047  →  ['TCS']
    CAND_0000056  →  ['TCS']
    CAND_0000059  →  ['TCS']
    CAND_0000062  →  ['Tech Mahindra']
    CAND_0000068  →  ['HCL']

── COMBINED EXCLUSION SUMMARY ──
  Non-India (no relocation):          17,735
  Wrong title:                        63,049
  Too junior (< 3 yoe):              16,105
  Too senior (> 15 yoe):                  7
  Null/empty skills:                       0
  Honeypot skill signal:                  21
  Pure consulting career:              9,737
  ─────────────────────────────────────────
  Union (unique excluded):            77,905  (78.0%)
  Remaining after ALL filters:        21,975

In [30]:
import json
from collections import Counter

jsonl_path = '../data/candidates_excluding_sample.jsonl'

WRONG_TITLE_KEYWORDS = [
    "marketing", "sales", "hr ", "human resource", "recruiter", "talent acquisition",
    "finance", "accountant", "accounting", "business development", "bd manager",
    "supply chain", "logistics", "operations manager", "project manager",
    "product manager",
    "graphic design", "ux designer", "ui designer", "visual design",
    "content writer", "copywriter", "seo", "social media",
    "civil engineer", "mechanical engineer", "electrical engineer",
    "hardware engineer", "embedded", "firmware",
    "computer vision", "cv engineer",
    "speech", "audio", "robotics", "autonomous",
    "teacher", "professor", "lecturer", "faculty",
    "doctor", "physician", "nurse", "pharmacist",
    "lawyer", "legal", "compliance",
    "customer success", "customer support", "support engineer",
]

# ── Consulting firms from the JD's explicit disqualifier list ─────────────────
PURE_CONSULTING_FIRMS = {
    "tcs", "tata consultancy", "infosys", "wipro", "accenture",
    "cognizant", "capgemini", "hcl", "tech mahindra", "mphasis",
    "hexaware", "mindtree", "ltimindtree", "l&t infotech",
    "persistent systems", "niit technologies", "mastech",
    "kforce", "syntel", "unison",
}

INDIA_VARIANTS = {"india", "in", "ind"}

def matches_any(text, keywords):
    return any(kw in text.lower() for kw in keywords)

def is_consulting_firm(company_name):
    c = company_name.lower().strip()
    return any(firm in c for firm in PURE_CONSULTING_FIRMS)

def is_pure_consulting_career(career_history):
    """
    Returns True only if EVERY role in career history is at a consulting firm.
    If even one role is at a product company → keep the candidate (JD says that's fine).
    """
    if not career_history:
        return False
    return all(is_consulting_firm(role.get("company", "")) for role in career_history)

def is_job_hopper(career_history):
    """
    Returns (bool, reason_str) 
    Flags if BOTH conditions are true:
      1. Average tenure across all roles < 18 months
      2. 3+ company switches (distinct companies)
    """
    if not career_history or len(career_history) < 2:
        return False, ""

    # ── condition 1: average tenure ──────────────────────────────────────────
    durations = [r.get("duration_months") or 0 for r in career_history]
    avg_tenure = sum(durations) / len(durations)

    # ── condition 2: distinct company switches ────────────────────────────────
    companies = [r.get("company", "").strip().lower() for r in career_history]
    unique_companies = set(companies)
    switches = len(unique_companies)

    if avg_tenure < 18 and switches >= 3:
        return True, f"avg_tenure={avg_tenure:.1f}mo, switches={switches}"

    return False, ""


def is_title_chaser(career_history):
    """
    Returns (bool, reason_str)
    Detects Senior → Staff → Principal progression across SHORT stints.
    Flags if:
      - 2+ title-level jumps detected (junior→mid, mid→senior, senior→staff, etc.)
      - AND each of those jumping roles lasted < 18 months
    """
    TITLE_LEVELS = {
        # level 1
        "junior": 1, "associate": 1, "intern": 1, "trainee": 1,
        # level 2
        "engineer": 2, "developer": 2, "analyst": 2, "scientist": 2,
        # level 3
        "senior": 3, "sr.": 3, "sr ": 3, "lead": 3,
        # level 4
        "staff": 4, "specialist": 4, "expert": 4,
        # level 5
        "principal": 5, "architect": 5,
        # level 6
        "director": 6, "vp": 6, "head": 6, "manager": 6,
    }

    def title_level(title):
        t = title.lower()
        matched = [lvl for kw, lvl in TITLE_LEVELS.items() if kw in t]
        return max(matched) if matched else 0

    # sort by start_date ascending to get chronological order
    sorted_career = sorted(
        career_history,
        key=lambda r: r.get("start_date") or "0000-00-00"
    )

    jumps = 0
    prev_level = 0
    for role in sorted_career:
        level = title_level(role.get("title", ""))
        duration = role.get("duration_months") or 0
        if level > prev_level and prev_level != 0 and duration < 18:
            jumps += 1
        prev_level = max(prev_level, level)

    if jumps >= 2:
        titles = [r.get("title", "") for r in sorted_career]
        return True, f"quick_jumps={jumps}, titles={titles}"

    return False, ""

# ── Thresholds ────────────────────────────────────────────────────────────────
MIN_YOE = 3
MAX_YOE = 15

# ── Counters & buckets ────────────────────────────────────────────────────────
country_counter     = Counter()
title_counter       = Counter()
yoe_distribution    = Counter()
consulting_firm_counter = Counter()  # frequency of consulting firms seen

non_india_ids        = []
wrong_title_ids      = []
too_junior_ids       = []
too_senior_ids       = []
honeypot_skill_ids   = []
null_skills_ids      = []
pure_consulting_ids  = []
job_hopper_ids      = []
title_chaser_ids    = []
total = 0
passed = []

with open(jsonl_path) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        c = json.loads(line)
        total += 1
        p             = c["profile"]
        cid           = c["candidate_id"]
        career        = c.get("career_history") or []

        country = p.get("country", "").strip()
        title   = p.get("current_title", "").strip()
        yoe     = p.get("years_of_experience", 0) or 0
        skills  = c.get("skills") or []

        bucket = (int(yoe) // 2) * 2
        yoe_distribution[bucket] += 1

        exclude_reasons = []

        # ── Filter 1: country ─────────────────────────────────────────────────
        country_counter[country] += 1
        if country.lower() not in INDIA_VARIANTS:
            willing = c.get("redrob_signals", {}).get("willing_to_relocate", False)
            if not willing:
                non_india_ids.append((cid, country))
                exclude_reasons.append("non_india")

        # ── Filter 2: wrong title ─────────────────────────────────────────────
        title_counter[title] += 1
        if matches_any(title, WRONG_TITLE_KEYWORDS):
            wrong_title_ids.append((cid, title))
            exclude_reasons.append("wrong_title")

        # ── Filter 3: years of experience extremes ────────────────────────────
        if yoe < MIN_YOE:
            too_junior_ids.append((cid, yoe))
            exclude_reasons.append("too_junior")
        elif yoe > MAX_YOE:
            too_senior_ids.append((cid, yoe))
            exclude_reasons.append("too_senior")

        # ── Filter 4: null / empty skills ────────────────────────────────────
        if not skills:
            null_skills_ids.append(cid)
            exclude_reasons.append("null_skills")

        # ── Filter 5: honeypot skill signal ───────────────────────────────────
        if skills:
            expert_skills = [s for s in skills if s.get("proficiency") == "expert"]
            if expert_skills and all(
                (s.get("duration_months") or 0) == 0 for s in expert_skills
            ):
                honeypot_skill_ids.append(
                    (cid, [(s["name"], s.get("duration_months")) for s in expert_skills])
                )
                exclude_reasons.append("honeypot_skill")

        # ── Filter 6: pure consulting career ─────────────────────────────────
        # count firm appearances regardless (for the frequency report)
        for role in career:
            company = role.get("company", "")
            if is_consulting_firm(company):
                consulting_firm_counter[company] += 1

        if is_pure_consulting_career(career):
            companies = [r.get("company", "") for r in career]
            pure_consulting_ids.append((cid, companies))
            exclude_reasons.append("pure_consulting")

        if not exclude_reasons:
            passed.append(cid)
# inside your main with open(jsonl_path) loop, after career is loaded

# ── Filter 7: job hopper ──────────────────────────────────────────────────────
hopper, hopper_reason = is_job_hopper(career)
if hopper:
    job_hopper_ids.append((cid, hopper_reason))
    exclude_reasons.append("job_hopper")

# ── Filter 8: title chaser ────────────────────────────────────────────────────
chaser, chaser_reason = is_title_chaser(career)
if chaser:
    title_chaser_ids.append((cid, chaser_reason))
    exclude_reasons.append("title_chaser")
# ── Results ───────────────────────────────────────────────────────────────────

print("=" * 60)
print(f"TOTAL CANDIDATES: {total:,}")
print("=" * 60)

# YOE distribution
print("\n── YEARS OF EXPERIENCE DISTRIBUTION ──")
print(f"  {'YOE bucket':<15} {'count':>7}   bar")
for bucket in sorted(yoe_distribution):
    cnt = yoe_distribution[bucket]
    bar = "█" * (cnt // 200)
    label = f"{bucket}-{bucket+1}"
    marker = " ← MIN cutoff" if bucket == int(MIN_YOE // 2) * 2 else \
             " ← MAX cutoff" if bucket == int(MAX_YOE // 2) * 2 else ""
    print(f"  {label:<15} {cnt:>7,}   {bar}{marker}")
print(f"\n  Too junior (< {MIN_YOE} yoe):  {len(too_junior_ids):,}")
print(f"  Too senior (> {MAX_YOE} yoe): {len(too_senior_ids):,}")

# Null skills
print(f"\n── NULL / EMPTY SKILLS ──")
print(f"  Candidates with no skills listed: {len(null_skills_ids):,}")

# Honeypot skills
print(f"\n── HONEYPOT SKILL SIGNAL ──")
print(f"  Candidates with ALL expert skills at duration_months=0: {len(honeypot_skill_ids):,}")
print("  Sample (first 10):")
for cid, skills_info in honeypot_skill_ids[:10]:
    print(f"    {cid}  →  {skills_info}")

# Consulting firms
print(f"\n── CONSULTING FIRM FREQUENCY (all appearances in career history) ──")
for firm, cnt in consulting_firm_counter.most_common():
    print(f"  {firm:<40} {cnt:>6,}")
print(f"\n  Candidates with PURE consulting career: {len(pure_consulting_ids):,}")
print("  Sample (first 10):")
for cid, companies in pure_consulting_ids[:10]:
    print(f"    {cid}  →  {companies}")

# Combined
excluded_ids = (
    set(cid for cid, _ in non_india_ids)
    | set(cid for cid, _ in wrong_title_ids)
    | set(cid for cid, _ in too_junior_ids)
    | set(cid for cid, _ in too_senior_ids)
    | set(null_skills_ids)
    | set(cid for cid, _ in honeypot_skill_ids)
    | set(cid for cid, _ in pure_consulting_ids)
)

print(f"\n── COMBINED EXCLUSION SUMMARY ──")
print(f"  Non-India (no relocation):          {len(non_india_ids):>6,}")
print(f"  Wrong title:                        {len(wrong_title_ids):>6,}")
print(f"  Too junior (< {MIN_YOE} yoe):              {len(too_junior_ids):>6,}")
print(f"  Too senior (> {MAX_YOE} yoe):             {len(too_senior_ids):>6,}")
print(f"  Null/empty skills:                  {len(null_skills_ids):>6,}")
print(f"  Honeypot skill signal:              {len(honeypot_skill_ids):>6,}")
print(f"  Pure consulting career:             {len(pure_consulting_ids):>6,}")
print(f"  ─────────────────────────────────────────")
print(f"  Union (unique excluded):            {len(excluded_ids):>6,}  ({len(excluded_ids)/total*100:.1f}%)")
print(f"  Remaining after ALL filters:        {len(passed):>6,}")

print(f"  Job hopper:                         {len(job_hopper_ids):>6,}")
print(f"  Title chaser:                       {len(title_chaser_ids):>6,}")

============================================================
TOTAL CANDIDATES: 99,880
============================================================

── YEARS OF EXPERIENCE DISTRIBUTION ──
  YOE bucket        count   bar
  0-1               7,465   █████████████████████████████████████
  2-3              17,557   ███████████████████████████████████████████████████████████████████████████████████████ ← MIN cutoff
  4-5              17,448   ███████████████████████████████████████████████████████████████████████████████████████
  6-7              17,227   ██████████████████████████████████████████████████████████████████████████████████████
  8-9              15,267   ████████████████████████████████████████████████████████████████████████████
  10-11            10,064   ██████████████████████████████████████████████████
  12-13             9,700   ████████████████████████████████████████████████
  14-15             5,147   █████████████████████████ ← MAX cutoff
  16-17                 5

  Too junior (< 3 yoe):  16,105
  Too senior (> 15 yoe): 7

── NULL / EMPTY SKILLS ──
  Candidates with no skills listed: 0

── HONEYPOT SKILL SIGNAL ──
  Candidates with ALL expert skills at duration_months=0: 21
  Sample (first 10):
    CAND_0003582  →  [('MLflow', 0), ('Photoshop', 0), ('Content Writing', 0)]
    CAND_0016000  →  [('TypeScript', 0), ('Go', 0), ('Docker', 0), ('Hadoop', 0), ('Photoshop', 0)]
    CAND_0033817  →  [('JavaScript', 0), ('BigQuery', 0), ('Six Sigma', 0), ('gRPC', 0)]
    CAND_0033972  →  [('Airflow', 0), ('OpenCV', 0), ('Figma', 0)]
    CAND_0036839  →  [('SAP', 0), ('GCP', 0), ('Rust', 0)]
    CAND_0042245  →  [('Databricks', 0), ('BentoML', 0), ('Vue.js', 0)]
    CAND_0046649  →  [('SAP', 0), ('Node.js', 0), ('gRPC', 0), ('Flask', 0), ('Hadoop', 0)]
    CAND_0046689  →  [('Node.js', 0), ('SQL', 0), ('gRPC', 0), ('Spark', 0)]
    CAND_0048740  →  [('gRPC', 0), ('Angular', 0), ('Content Writing', 0)]
    CAND_0055792  →  [('Scrum', 0), ('TTS', 0), ('LoRA', 0)]

── CONSULTING FIRM FREQUENCY (all appearances in career history) ──
  Infosys                                  23,693
  Wipro                                    23,645
  TCS                                      23,459
  HCL                                       2,892
  Capgemini                                 2,884
  Mindtree                                  2,876
  Accenture                                 2,868
  Cognizant                                 2,858
  Tech Mahindra                             2,834
  Mphasis                                   2,820

  Candidates with PURE consulting career: 9,737
  Sample (first 10):
    CAND_0000003  →  ['TCS']
    CAND_0000008  →  ['Wipro']
    CAND_0000024  →  ['TCS', 'Infosys']
    CAND_0000027  →  ['Infosys', 'Wipro']
    CAND_0000028  →  ['Wipro']
    CAND_0000047  →  ['TCS']
    CAND_0000056  →  ['TCS']
    CAND_0000059  →  ['TCS']
    CAND_0000062  →  ['Tech Mahindra']
    CAND_0000068  →  ['HCL']

── COMBINED EXCLUSION SUMMARY ──
  Non-India (no relocation):          17,735
  Wrong title:                        63,049
  Too junior (< 3 yoe):              16,105
  Too senior (> 15 yoe):                  7
  Null/empty skills:                       0
  Honeypot skill signal:                  21
  Pure consulting career:              9,737
  ─────────────────────────────────────────
  Union (unique excluded):            77,905  (78.0%)
  Remaining after ALL filters:        21,975
  Job hopper:                              0
  Title chaser:                            0